name: build

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    test:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        strategy:
            fail-fast: false
            matrix:
                php: [ 8.4, 8.3, 8.2 ]
                laravel: [ 12.*, 11.*, 10.*]
                dependency-version: [ prefer-stable ]
                os: [ ubuntu-latest ]
                include:
                    -   laravel: 12.*
                        testbench: 10.*
                    -   laravel: 11.*
                        testbench: 9.*
                    -   laravel: 10.*
                        testbench: 8.*
                    -   php: 8.4
                        unitconfig: phpunit_gt_81.xml
                    -   php: 8.3
                        unitconfig: phpunit_gt_81.xml
                    -   php: 8.2
                        unitconfig: phpunit_gt_81.xml
                exclude:
                    -   laravel: 10.*
                        php: 8.4
        runs-on: ${{ matrix.os }}
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        env:
            extensions: intl, json, mbstring, dom, curl, openssl

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP extensions
                id: cache-env
                uses: shivammathur/cache-extensions@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.extensions }}
                    key: php-extensions-cache-v1

            -   name: Setup PHP  ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.extensions }}
                    tools: composer
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Setup Laravel ${{ matrix.laravel }}
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Run tests
                run: |
                    vendor/bin/phpunit -c ${{ matrix.unitconfig }} --coverage-clover=coverage.clover